config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # 仮のルーティング
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    collection do
      get 'events/get_category_children', defaults: { format: 'json' }
      get 'events/get_category_grandchildren', defaults: { format: 'json' }
      # get 'confirmation'
      # resources :messages
    end
    member do
      get 'confirmation'
      post 'buy'
      get 'done'
    end
    # seedで仮情報をイベントテーブルに入れたらこの位置に記述を移す
    resources :messages
    resources :entries
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

     
  resources :users, only: [:show, :edit] do
    collection do
      post 'show', to: 'users#show'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 予約したイベント、現在出展中のイベント、すでに予約済のイベントの条件付きアソシエーション
  has_many :buyed_events, foreign_key: "buyer_id", class_name: "Event"
  has_many :exhibiting_events, -> { where("buyer_id is NULL") }, foreign_key: "exhibitor_id", class_name: "Event"
  has_many :reserved_events, -> { where("buyer_id is not NULL") }, foreign_key: "exhibitor_id", class_name: "Event"
  
  has_many :messages,dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :comments
  has_many :cards
  has_many :events, through: :entries
  has_many :events, through: :messages
  has_one  :personal
  accepts_nested_attributes_for :personal
  has_one :address
  accepts_nested_attributes_for :address
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(current_user.id)
    # # 自分が参加しているメッセージルーム情報を取得する
    # @currentUserEntry = Entry.where(user_id: current_user.id)
    # #選択したユーザのメッセージルーム情報を取得する
    # @userEntry = Entry.where(event_id: event.id).where('user_id!=?',@user.id)
    # binding.pry
    # #current_userと選択したユーザ間に共通のメッセージルームが存在すればフラグを立てる
    # unless @user.id == current_user.id
    #   @currentUserEntry.each do |cu|
    #     @userEntry.each do |u|
    #       if cu.event_id == u.event_id then
    #         @isEvent = true
    #         @eventId = cu.event_id

    #       end
    #     end
    #   end
    #   #存在しなければ作る
    #   unless @isEvent
    #     binding.pry
    @event = Event.new
    @entry = Entry.new
    #   end
    # end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="user-container">
  <%= render partial: 'shared/main_header' %>
  <div class="l-container clearfix">
    <div class="l-content">
      <section class="user-menu">
        <h2 class="user-title">
          <%= @user.nickname + "さんのページ"%>
        </h2> 
        <%# ここの部分で余裕あったらマイページを作成 %>
        <div class="user-dm-start">
          <%= form_for @event, :url => {:action => :create, :controller => :events} do |f| %>
          <%# <%= form_with url: events_path, local: true do |f| %>
            <%= f.hidden_field :nickname, :value => @user.nickname %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, :value => @user.id %>
            <% end %> 
            <%= f.submit "ダイレクトメッセージを始める" ,class: "btn-default btn-green message-submit" %>
          <% end %>
        </div>
        <%# 一時的にここからカード情報登録ページに遷移させる %>
        <div class="payment-registration">
          <%= link_to new_card_path, class:"btn-default btn-green" do%>
            <i class="far fa-credit-card"></i>
              クレジットカードを追加する
          <% end %>
        </div>
      </section>
    </div>
  </div>
</div>