config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # 仮のルーティング
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    collection do
      get 'events/get_category_children', defaults: { format: 'json' }
      get 'events/get_category_grandchildren', defaults: { format: 'json' }
      # get 'confirmation'
      # resources :messages
    end
    member do
      get 'confirmation'
      post 'buy'
      get 'done'
    end
    # seedで仮情報をイベントテーブルに入れたらこの位置に記述を移す
    resources :messages
    resources :entries
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

     
  resources :users, only: [:show, :edit] do
    collection do
      post 'show', to: 'users#show'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :event
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events
  has_ancestry
end

app/models/cook.rb
class Cook < ApplicationRecord
  belongs_to :event
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_many :images
  accepts_nested_attributes_for :images
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :exhibitor, class_name: "User"
  belongs_to :buyer, class_name: "User",optional: true
  belongs_to :prefecture
  belongs_to :category
  has_many :messages,  dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :images,dependent: :destroy
  has_one :cook
  has_one :address
  has_many :users, through: :messages
  has_many :users, through: :entries

  #イメージ・開催場所日時・料理工程選択をDB登録するために記載
  accepts_nested_attributes_for :images,allow_destroy: true
  accepts_nested_attributes_for :cook
  accepts_nested_attributes_for :address
  
  validates_associated :images
  validates :images, presence: true

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :event,optional: true
  mount_uploader :content, ImageUploader
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :users
  has_many :items
  has_many :personals
  has_many :addresses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 予約したイベント、現在出展中のイベント、すでに予約済のイベントの条件付きアソシエーション
  has_many :buyed_events, foreign_key: "buyer_id", class_name: "Event"
  has_many :exhibiting_events, -> { where("buyer_id is NULL") }, foreign_key: "exhibitor_id", class_name: "Event"
  has_many :reserved_events, -> { where("buyer_id is not NULL") }, foreign_key: "exhibitor_id", class_name: "Event"
  
  has_many :messages,dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :comments
  has_many :cards
  has_many :events, through: :entries
  has_many :events, through: :messages
  has_one  :personal
  accepts_nested_attributes_for :personal
  has_one :address
  accepts_nested_attributes_for :address
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  require "payjp" 
  # before_action :set_card

  def new
    # cardがすでに登録済みの場合、showのページに戻します。
    @card = Card.new
    @card = Card.where(user_id: current_user.id).first
    redirect_to action: "show" if @card.present?    
  end

  def pay
    # payjpとCardのデータベースを作成する
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    # jsで作成したpayjpTokenがちゃんと入っているか？
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      # トークンがちゃんとあれば進めて、PAY.JPに登録されるユーザーを作成します。
      customer = Payjp::Customer.create(
      # description: '登録テスト',  # なくてもOK
      # email: current_user.email, # なくてもOK
      # metadata: {user_id: current_user.id} # なくてもOK
      # 直前のnewアクションで発行され、送られてくるトークンをここで顧客に紐付けて永久保存する
      card: params['payjp-token']
      
      )
      # PAY.JPのユーザーが作成できたので、cardモデルを登録します。
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      @card.save
      if @card.save
        redirect_to cards_path, notice: '登録が完了しました'

      else
        redirect_to action: "pay"
      end
    end
  end

  def show
    @card = Card.where(user_id: current_user.id).first
    # すでにクレジットカードが登録しているか？  
    if @card.present?
      # 登録している場合,PAY.JPからカード情報を取得する
      # PAY.JPの秘密鍵をセットする。
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      # PAY.JPから顧客情報を取得する。
      customer = Payjp::Customer.retrieve(@card.customer_id)
      # PAY.JPの顧客情報から、デフォルトで使うクレジットカードを取得する。
      @card_info = customer.cards.retrieve(@card.card_id)
      # クレジットカード情報から表示させたい情報を定義する。
      # クレジットカードの画像を表示するために、カード会社を取得
      @card_brand = @card_info.brand
      # クレジットカードの有効期限を取得
      @exp_month = @card_info.exp_month.to_s
      @exp_year = @card_info.exp_year.to_s.slice(2,3)

      # クレジットカード会社を取得したので、カード会社の画像をviewに表示させるため、ファイルを指定する。
      # カードブランドうまく分けられる様になったらコメントアウト外す
      # case @card_brand
      # when "Visa"
      #   @card_image = "visa.svg"
      # when "JCB"
      #   @card_image = "jcb.svg"
      # when "MasterCard"
      #   @card_image = "master-card.svg"
      # when "American Express"
      #   @card_image = "american_express.svg"
      # when "Diners Club"
      #   @card_image = "dinersclub.svg"
      # when "Discover"
      #   @card_image = "discover.svg"
      # end
    end
  end

  def delete
    # 今回はクレジットカードを削除するだけでなく、PAY.JPの顧客情報も削除する。これによりpayメソッドが複雑にならない。
    # PAY.JPの秘密鍵をセットして、PAY.JPから情報をする。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    # PAY.JPの顧客情報を取得
    customer = Payjp::Customer.retrieve(@card.customer_id)
    customer.delete # PAY.JPの顧客情報を削除
    if @card.destroy # App上でもクレジットカードを削除
      redirect_to users_path, notice: "削除しました"
    else
      redirect_to users_path, alert: "削除できませんでした"
    end
  end

  private

  # def set_card
  #   @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  # end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def index
    if user_signed_in?
      @user = User.find(current_user.id)
    else
      @user = User.new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exhibits_helper.rb
module ExhibitsHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div class='notifications'>
  <%# 投稿成功の場合、keyに"notice"、valueに"メッセージが送信されました"が入る %>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: key) %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RyoutokuApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://js.pay.jp/",type="text/javascript"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render partial: 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_common_header.html.erb
<div class="common-header">
  <%= link_to root_path do%>
    <h1 id= "toppage-logo" class= "toppage-logo">Ryoutoku</h1>
    <br>
  <% end %>
</div>

app/views/shared/_exhibit_btn.html.erb
<%= link_to new_event_path ,class: "footer-exhibit-btn" do %>
  <div>出展</div>
  <i class="fas fa-chalkboard-teacher"></i>
<% end %>

app/views/shared/_main_header.html.erb
<div class="header-container">
  <div class="join-menu">
    <%# 仮でイベント詳細ページに遷移、のちにイベント一覧ページを作成し、遷移先を変更 %>
    <% if user_signed_in? %> 
      <%= link_to root_path, class: "join-btn" do %>
        <i class="fas fa-home"></i>
        <span>ホーム</span>
      <% end %>
    <% else %>
      <%= link_to root_path, class: "join-btn" do %>
      <i class="fas fa-home"></i>
      <span>ホーム</span>
      <% end %>
    <% end %>
  </div>
    <% if user_signed_in? %> 
      <%# ログイン時 %>
      <div class="nav-menu">
        <div class="user-information">
          <%# ここはマイページ画面に遷移するパスを入れる予定 %>
          <%= link_to user_path(id: current_user.id), class:"user-icon" do %>
            <%# あとでここにアイコンの写真が入るようにする %>
            <% if current_user.icon.nil? %>
              <%= image_tag 'mrkr-icon.png' %>
            <% else %>
              <%= image_tag current_user.icon %>
            <% end %>
          <% end %>
        </div>
        <div class="user-information">
          <span><%= current_user.nickname %></span>
        </div>
        <%# 仮置きのクラス、あとでログアウトページも作る予定 %>
        <div class="user-logout">
         <%=  link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn-default btn-green"%>        
      </div> 
    <% else %> 
      <%# 未ログイン時 %>
      <div class="nav-menu">
        <%= link_to '新規会員','/users/sign_up',class: "nav-menu__registration"%> 

        <%= link_to 'ログイン','/users/sign_in',class: "nav-menu__login"%>
      </div>
    <% end %>

</div>

app/views/shared/_sidebar.html.erb
<div class="event-side">
  <div class="event-side__detail">
    <div class="event-side__detail--images">
      <%= image_tag 'cookingimage1.png',style: "width: 280px; height: 250px;" %>
      <%# ここに複数のイベント写真を載せる予定 %>
      <div class="event-small-images">
        <%= image_tag 'cookingimage2.png' %>
      </div>
    </div>
    <div class="information-event_content-image2">
    </div>
    <table class="event-detail-table">
      <tbody>
        <tr>
          <th>出展者</th>
          <td>
            <%= link_to "#" do %>
              <span>KA</span>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>開催日程</th>
          <td>
            <div class="event-detail__date">
              2月29日（土）
            <div class="event-detail__time">
              18:30-20:30
          </td>
        </tr>
        <tr>
          <th>場所</th>
          <td>
            <div class="event-detail__place">
              地下鉄 明治神宮駅 徒歩3分
            </div>
          </td>
        </tr>
        <tr>
          <th>参加する人</th>
          <td>
            <div class="participants">
              <div class="photo-participants">
                <%= image_tag 'mrkr-icon.png' %>
                <span>momoko</span>
                <%= image_tag 'mrkr-icon.png' %>
                <span>tae</span>
                <%= image_tag 'mrkr-icon.png' %>
                <span>KA</span>
                <%= image_tag 'mrkr-icon.png' %>
                <span>ayumu</span>
                <%= image_tag 'mrkr-icon.png' %>
                <span>shinnosuke</span>
              </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="cooking">
              <div class="cooking-participants">
                料理する人
                <tr>
                <td>tae</td>
                <td>具材買い出しの手伝い</td>
                </tr>
                <tr>
                <td>momoko</td>
                <td>キャベツを切って下ゆでする</td>
                </tr>
                <tr>
                <td>KA</td>
                <td>玉ねぎ・人参をみじん切りする</td>
                </tr>
                <tr>
                <td>ayumu</td>
                <td>豚ひき肉と野菜を混ぜて肉ダネを作る</td>
                </tr>
                <tr>
                <td>tae</td>
                <td>肉ダネをキャベツで巻き出汁を取ったスープで茹でる</td>
              </div>
            </div>
          </td>
        </tr>

      </tbody>
    </table>
  </div>
</div>