config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # 仮のルーティング
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    collection do
      get 'events/get_category_children', defaults: { format: 'json' }
      get 'events/get_category_grandchildren', defaults: { format: 'json' }
      # get 'confirmation'
      # resources :messages
    end
    member do
      get 'confirmation'
      post 'buy'
      get 'done'
    end
    # seedで仮情報をイベントテーブルに入れたらこの位置に記述を移す
    resources :messages
    resources :entries
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

     
  resources :users, only: [:show, :edit] do
    collection do
      post 'show', to: 'users#show'
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :exhibitor, class_name: "User"
  belongs_to :buyer, class_name: "User",optional: true
  belongs_to :prefecture
  belongs_to :category
  has_many :messages,  dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :images,dependent: :destroy
  has_one :cook
  has_one :address
  has_many :users, through: :messages
  has_many :users, through: :entries

  #イメージ・開催場所日時・料理工程選択をDB登録するために記載
  accepts_nested_attributes_for :images,allow_destroy: true
  accepts_nested_attributes_for :cook
  accepts_nested_attributes_for :address
  
  validates_associated :images
  validates :images, presence: true

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!,except: [:index,:show]
  before_action :get_user
  before_action :set_event,only: [:confirmation, :done,:edit, :update]

  def index
    #カテゴリーごとに並べる
    @meats = Event.includes(:images).where(category_id: 158..247).order("updated_at DESC").limit(10)
    @rices = Event.includes(:images).where(category_id: 275..342).order("updated_at DESC").limit(10)
    @breads = Event.includes(:images).where(category_id: 580..648).order("updated_at DESC").limit(10)
    @sweets = Event.includes(:images).where(category_id: 649..763).order("updated_at DESC").limit(10)
    if user_signed_in?
      # ログインユーザが持っている複数のentryをEntryテーブルから探して変数にいれます
      @entries = Entry.where(user_id: current_user.id)
      myEventIds = []
      # myEventIdsにログインユーザが持っているそれぞれのentryにおけるeventのid情報を渡す
      @entries.each do | entry |
        myEventIds << entry.event.id
      end
      @anotherEntries = Entry.where(event_id: myEventIds).where(user_id: @user.id).order("updated_at DESC").limit(10)
      # 自分が参加していないイベントを出した場合には下記の記述でOK
      # @anotherEntries = Entry.where(event_id: myEventIds).where('user_id != ?', @user.id).order("updated_at DESC").limit(10)
    end
  end

  def create
    @event = Event.new(event_params)
    @event.save
    if @event.save
      redirect_to root_path, notice: '出展が完了しました'
    else
      redirect_to new_event_path, alert: '出展が完了しておりません'
    end
    # ↓別のコントローラに移動させる
    # @entry1 = Entry.create(:event_id => @event.id, :user_id => current_user.id)
    # @entry2 = Entry.create(params.require(:entry).permit(:user_id, :event_id).merge(:event_id => @event.id))
  end

  # イベント出展画面
  def new
    @event = Event.new
    @event.images.build
    # @event.build_address
    # @event.build_cook
    @parents = Category.where(ancestry: nil)
  end

  # 子カテゴリーidを取得するためのアクション
  def get_category_children
    #親ボックスのidから子ボックスのidの配列を作成してインスタンス変数で定義
    @children = Category.find(params[:parent_id]).children
    respond_to do |format|
      format.html
      format.json { render 'new', json: @children }
    end
  end

  # 孫カテゴリーidを取得するためのアクション
  def get_category_grandchildren
    @grandchildren = Category.find(params[:child_id]).children
    respond_to do |format|
      format.html
      format.json { render 'new', json: @grandchildren}
    end
  end
  
  # イベント詳細画面
  def show
    @event = Event.find(params[:id])
    @user = User.find_by(id: @event.exhibitor_id)
    if user_signed_in?
      if Entry.where(:user_id => current_user.id, :event_id => @event.id).present?
        @messages = @event.messages.includes(:user)
        @message = Message.new
        @entries = @event.entries.includes(:user)
      else
        # redirect_back(fallback_location: root_path)

      end
    end
  end

  # イベント予約確認画面
  def confirmation
    @entry = Entry.new
    @card = Card.where(user_id: current_user.id).first
    # @events = Event.new
    if @card.present?
      # 登録している場合,PAY.JPからカード情報を取得する
      # PAY.JPの秘密鍵をセットする。
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      # PAY.JPから顧客情報を取得する。
      customer = Payjp::Customer.retrieve(@card.customer_id)
      # PAY.JPの顧客情報から、デフォルトで使うクレジットカードを取得する。
      @card_info = customer.cards.retrieve(@card.card_id)
      # クレジットカード情報から表示させたい情報を定義する。
      # クレジットカードの画像を表示するために、カード会社を取得
      @card_brand = @card_info.brand
      # クレジットカードの有効期限を取得
      @exp_month = @card_info.exp_month.to_s
      @exp_year = @card_info.exp_year.to_s.slice(2,3)
    end
  end

  # イベント予約の為にpayjpへ決済情報とトークンを送る際の定義を記述
  def buy
    @event = Event.find(params[:id])
    # @events = Event.new(:result => @event_result)
    # @events.save
    @entry = Entry.new(:event_id => @event.id, :user_id => current_user.id)
    @entry.save
    @card = Card.where(user_id: current_user.id).first
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    # 請求を発行
    charge = Payjp::Charge.create(
    amount: @event.price,#支払金額
    # amount: @event_result,#支払金額
    # customer:  @card.customer_id,#顧客ID
    card: params['payjp-token'],
    currency: 'jpy'
    )
    redirect_to action: :done
  end

  # イベント予約完了画面
  def done
    @entries = Entry.where(event_id: @event.id).count
    if @entries == @event.capacity
      @event_buyer = Event.find(params[:id])
      @event_buyer.update(buyer_id: current_user.id)
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :capacity,:place,:price,:result,:prefecture_id,:category_id, images_attributes: [:id, :event_id, :content, :_destroy ]).merge(exhibitor_id: current_user.id)
    #開催場所・日時・料理工程ページ作成したらpermitに入れる
    # ,address_attributes: [:id, :event_id, :date, :time, :postcode,:city,:address,:building,:phone_number,:figure],cook_attributes: [:id,:event_id,:level1,:level2,:level3,:level4,:level5]
  end

  def get_user
    if user_signed_in?
      @user = User.find(current_user.id)
    else
      @user = User.new
    end
  end



  def entry_params
    params.require(:entry).permit(:user_id, :event_id).merge(event_id: @event.id)
  end


  def set_event
    @event = Event.find(params[:id])
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/confirmation.html.erb
<div class="exhibit-container">
  <%= render partial: 'shared/common_header' %>
</div>
<div class="payment-container">
  <section class="payment_details">
    <h2 class="payment_details__title">予約内容の確認</h2>
    <%# <form class="payment-form" name="cooking_details"> %>
    <%= form_for [@event,@entry],url: buy_event_path, method: :post, html: {class: "payment-form",id: 'charge-form', name: "cooking_details"} do |f| %>
    <%# <%= form_for @event, html: {class: "payment-form",id: 'charge-form', name: "cooking_details"} do |f| %>
      <section class="payment_summary">
        <div class="payment_summary-inner">
          <h3 class="payment_summary-inner__photo">
            <%= image_tag 'mrkr-icon.png' %>
          </h3>
          <div class="payment_summary-inner__right">
            <p class="payment_summary-inner__right__event-name">管理栄養士による晩ごはん提供イベント</p>
            <p class="payment_summary-inner__exhibitor">KA</p>
          </div>
        </div>
      </section>
      <section class="payment_summary">
        <div class="payment_summary-inner">
          <ul>
            <li>
              <i class="fas fa-calendar-alt"></i>
              2月29日(土) 18:30 - 20:30
            </li>
          </ul>
        </div>
      </section>
      <section class="payment_summary">
        <div class="payment_summary-inner">
          <i class="fas fa-map-marker-alt"></i>
          <div class="payment_summary-inner__place">
            <p class="payment_summary-inner__place__train">地下鉄線 明治神宮前駅 徒歩3分</p>
            <p class="payment_summary-inner__place__address">
            〒555-5555
            <br>
            東京都 渋谷区 松本1-12-13 まつビル</p>
          </div>
        </div>
      </section>
      <section class="cooking_summary">
        <div class="cooking_summary-inner">
          <div class= "middle-icon">
            <i class="fas fa-mitten"></i>
            <h1>やってみたい料理工程を選択してください（２つまで）</h1>
          </div>
          <table class="cooking_summary-inner__table" border="0">
            <tr>
            <td>レベル１(500円割引)</td>
            <td><input type="checkbox" name="c2" onclick="keisan();Climit();update_price()">具材買い出しの手伝い</td>
            </tr>
            <tr>
            <td>レベル２(1000円割引)</td>
            <td><input type="checkbox" name="c2" onclick="keisan();Climit();update_price()">キャベツを切って下ゆでする</td>
            </tr>
            <tr>
            <td>レベル３(1500円割引)</td>
            <td><input type="checkbox" name="c2" onclick="keisan();Climit();update_price()">玉ねぎ・人参をみじん切りする</td>
            </tr>
            <tr>
            <td>レベル４(2000円割引)</td>
            <td><input type="checkbox" name="c2" onclick="keisan();Climit();update_price()">豚ひき肉と野菜を混ぜて肉ダネを作る</td>
            </tr>
            <tr>
            <td>レベル５(2500円割引)</td>
            <td><input type="checkbox" name="c2" onclick="keisan();Climit();update_price()">肉ダネをキャベツで巻き出汁を取ったスープで茹でる</td>
            </tr> 
            <tr>
            <td>価格</td>
            <%# ここで出展の時に登録した価格を表示させる %>
            <td>￥
            <%= f.text_field :price, value: @event.price ,id: "price" ,type: "text", size: "40",class: 'input-field' %>
            <%# <input id="price" type="text" size="40" value="" > %>
            </td>
            </tr>
            <td><font color="#ff0000">■</font><b><font color="#ff0000">割引金額</font></b></td>
            <td>￥
            <%# <%= f.text_field :total, value: "0" ,id: "discount" ,type: "text", size: "40",class: 'input-field' %>
            <input id="discount" type="text" name="total" value="0" >
            </td>
            </tr>
          </table>
          <div class="event_reservation__price">
            イベント予約価格 ￥
            <span class="total" id="total"></span> 
            <%# <input id="result" type="hidden" value="">  %>
            <%= f.hidden_field :result, value:@event_result,id: "result" ,class: 'result' %>
          </div>
        </div>
      </section>
      <div class="event-reservation-btn">
        <script class="payjp-button" src="https://checkout.pay.jp/" type="text/javascript" data-key="pk_test_738f868bb1bc43982dd03d7d" data-text="予約を確定する"></script>
      </div>
    <% end %>
    <%# </form> %>
  </section>
  <section class="event_reservation payment_fixed-footer">
    <div class="event_reservation-inner">
      <%# <div class="event_reservation-inner__price">
        イベント予約価格 ￥<span id="total" value="update"> </span>
      </div> %>
    <%# <div class="event-reservation-btn"> %>
      <%# <%= form_for @event, url: buy_event_path, method: :post, html: {class: “event-reservation-form”} do |f| %>
        <%# <script class="payjp-button" ,src="https://checkout.pay.jp/" ,type="text/javascript" ,data-key= "ENV["PAYJP_KEY"]" ,data-text="予約を確定する"></script> %>
      <%# <% end %>
      <%# 本来は予約確定画面に遷移だが、一時的にイベント参加者チャット画面に遷移 %>
      <%# <%= link_to event_messages_path(current_user.id), class:"btn-default btn-green" do%>
        <%# 予約を確定する %>
      <%# <% end %>
    <%# </div> %>
    <div class="payment-method">
      <h2 class="l-left">
        支払い方法
      </h2>
      <%= link_to new_card_path(current_user.id), class:"card-info-fix" do%>
        変更する
        <i class="fas fa-arrow-right"></i>
      <% end %>
      <ul class="settings-payment-list">
        <li>
          <div class="l-step-content">
            <% if @card.present? %>
              <%# <i class="fab fa-cc-visa"></i> %>
              <img src="//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?465897195", width="49", height="20">
              <br>
              <%= "**** **** **** " + @card_info.last4 %>
              <br>
                <%# 有効期限 %>
              <%= @exp_month + " / " + @exp_year %>
            <% else %>
              <%= " / " %>
            <% end %> 
          </div>
        </li>
      </ul>
    </div>
  </section> 
</div>
  

app/views/events/done.html.erb
<section class="event-box-container">
  <%= render partial: 'shared/common_header' %>
  <div class="header-icon">
    <i class="fas fa-mitten"></i>
  </div>
  <h1 class="event-name">予約が完了しました</h1>
    <p class="event-name__description"></p>
</section>

app/views/events/index.html.erb
<div class="header-top">
  <%= render partial: 'shared/main_header' %>
</div>
<div class= "toppage-container">
  <div class= "middle-content">
    <h1 id= "toppage-logo" class= "toppage-logo">料理体験シェアマッチングアプリ</h1>
    <%= link_to root_path do %>
      <svg version="1.1" id="logo" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 340.2 135.5" style="enable-background:new 0 0 340.2 135.5;" xml:space="preserve">
        <text x="0" y="50%">RYOUTOKU</text>
      </svg>       

    <% end %>
    <div class="slider">

    </div>
  </div>
  <div class="dm-index">
    <h3> 肉料理新着イベント</h3>
    <%= link_to "#" do %>
      もっと見る
      <i class="fas fa-chevron-right"></i>
    <% end %>
  </div>
  <div class="event-index">
    <ul class="event-index__list">
      <%# データベースからカテゴリーごとに並べる時に使用 %>
      <% @meats.each do |meat| %>
        <%#<%= Message.find_by(id: entry.event.message_ids.last).content %> 
        <li class="event-index__item">  
          <%=link_to event_path(meat),class: "events-link" do %>
            <div class="event-box">
              <span><%= meat.prefecture.name %>
              </span>
              <%# 画像アップロードするエリア %>
              <%# <%= image_tag "ryouri6.jpeg" %>
              <% if meat.images.present? %> 
                <%= image_tag (meat.images.first.content.url)unless meat.images.first.content.nil? %>
              <% end %>
            </div>
            <div class="event-title"> 
              <%= meat.title + ""%>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div> 
  <div class="dm-index">
    <h3> ごはんもの新着イベント</h3>
    <%= link_to "#" do %>
      もっと見る
      <i class="fas fa-chevron-right"></i>
    <% end %>
  </div>
  <div class="event-index">
    <ul class="event-index__list">
      <%# データベースからカテゴリーごとに並べる時に使用 %>
      <% @rices.each do |rice| %>
        <%#<%= Message.find_by(id: entry.event.message_ids.last).content %> 
        <li class="event-index__item">  
          <%=link_to event_path(rice),class: "events-link" do %>
            <div class="event-box">
              <span><%= rice.prefecture.name %>
              </span>
              <%# 画像アップロードするエリア %>
              <%# <%= image_tag "ryouri6.jpeg" %>
              <% if rice.images.present? %> 
                <%= image_tag (rice.images.first.content.url)unless rice.images.first.content.nil? %>
              <% end %>
            </div>
            <div class="event-title"> 
              <%= rice.title + ""%>
            </div>  
          <% end %>
        </li>
      <% end %>
    </ul>
  </div> 
  <div class="dm-index">
    <h3> パン料理新着イベント</h3>
    <%= link_to "#" do %>
      もっと見る
      <i class="fas fa-chevron-right"></i>
    <% end %>
  </div>
  <div class="event-index">
    <ul class="event-index__list">
      <%# データベースからカテゴリーごとに並べる時に使用 %>
      <% @breads.each do |bread| %>
        <%#<%= Message.find_by(id: entry.event.message_ids.last).content %> 
        <li class="event-index__item">  
          <%=link_to event_path(bread),class: "events-link" do %>
            <div class="event-box">
              <span><%= bread.prefecture.name %>
              </span>
              <%# 画像アップロードするエリア %>
              <%# <%= image_tag "ryouri6.jpeg" %>
              <% if bread.images.present? %> 
                <%= image_tag (bread.images.first.content.url)unless bread.images.first.content.nil? %>
              <% end %>
            </div>
            <div class="event-title"> 
              <%= bread.title + ""%>
            </div>  
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="dm-index">
    <h3> スイーツ料理新着イベント</h3>
    <%= link_to "#" do %>
      もっと見る
      <i class="fas fa-chevron-right"></i>
    <% end %>
  </div>
  <div class="event-index">
    <ul class="event-index__list">
      <%# データベースからカテゴリーごとに並べる時に使用 %>
      <% @sweets.each do |sweet| %>
        <%#<%= Message.find_by(id: entry.event.message_ids.last).content %> 
        <li class="event-index__item">  
          <%=link_to event_path(sweet),class: "events-link" do %>
            <div class="event-box">
              <span><%= sweet.prefecture.name %>
              </span>
              <%# 画像アップロードするエリア %>
              <%# <%= image_tag "ryouri6.jpeg" %>
              <% if sweet.images.present? %> 
                <%= image_tag (sweet.images.first.content.url)unless sweet.images.first.content.nil? %>
              <% end %>
            </div>
            <div class="event-title"> 
              <%= sweet.title + ""%>
            </div>  
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="dm-index">
    <% if user_signed_in? %>
      <div>
        <%= @user.nickname + 'さんが参加中のイベント一覧' %>
      </div>
      <%= link_to "#" do %>
        もっと見る
        <i class="fas fa-chevron-right"></i>
      <% end %>
    <% end %>
  </div>
  <% if user_signed_in? %> 
    <div class="event-index">
      <ul class="event-index__list">
        <%# データベースから並べる時に使用 %> 
        <% @anotherEntries.each do |entry| %>
          <li class="event-index__item">  
            <%=link_to event_messages_path(entry.event),class: "events-link" do %>
              <div class="event-box">
                <span><%= entry.event.prefecture.name %>
                </span>
                <%# 画像アップロードするエリア %>
                <%= image_tag(entry.event.images.first.content.url)unless entry.event.images.first.content.nil? %>
              </div>
              <div class="event-title"> 
                <%= entry.event.title + ""%>
              </div>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %> 
</div>


<%= render partial: 'shared/exhibit_btn'%> 

app/views/events/new.html.erb
<div class="exhibit-container">
  <%= render partial: 'shared/main_header' %>
</div>
<div class="event-container">
  <div class="event-content">
    <div class="event-content__title">
      <i class="fas fa-chalkboard-teacher"></i>
      <span>イベントを作る！</span>
      <%# ユーザーログイン機能を作成したらform_withを使う %>
    </div>
    <%= form_for @event do |f| %>
      <div class="event-images">
        <div class="event-images__title">
          <label>出展画像
          <span>必須</span>
        </div>
        <p class="event-images__text">
          最大５枚までアップロードできます
        </p>
        <%# 画像アップロードするエリア %>
        <div id="image-box-1">
          <div class="dropzone-container event-num-0 clearfix" id="image-box__container" >
            <%= f.fields_for :images do |i|%>
              <%# <%= f.label :content,for:"img-file" %>
              <%= i.file_field :content,name: "event[images_attributes][][content]",value:"",style: "display:none",type: "file",id:"img-file" %>
              <label for="img-file">
                <i class="fas fa-camera"></i>
            <% end %>
          </div>
        </div>
        <div class="event-images__name">
          <%= f.label :イベント名 %>
          <span class="icon-default">必須</span><br>
          <%= f.text_area :title, class: 'input-default', placeholder: 'ここにイベント名を入力（４０文字以内）' %>
        </div>
        <div class="event-images__description">
          <%= f.label :イベントの説明 %>
          <span class="icon-default">必須</span><br>
          <%= f.text_area :description, class:'input-default description-box', placeholder: 'ここにイベントの説明を入力' %>
        </div>
        <div class="event-images-category">
          <%= f.label :カテゴリー %>
          <span class="icon-default">必須</span><br>
          <div class="event-images-category__detail category-add">
            <%= f.collection_select :category_id,@parents, :id, :name, {include_blank: "---"},class:'select-default', id: "parent-form",name: "event[category_id][]" %>
          </div>
          <div class="detail-add-content">
          </div>
          <div class="detail-add-content2">
          </div>
        <div class="event-images-exhibit-area">
          <%= f.label :出展地域 %>
          <span class="icon-default">必須</span><br>
          <div class="event-images-exhibit-area__detail">
            <%= f.collection_select :prefecture_id,Prefecture.all, :id, :name, {include_blank: "---"},class:'select-default' %>
          </div>
        </div>
        <div class="event-images-capacity">
          <%= f.label :参加人数 %>
          <span class="icon-default">必須</span><br>
          <div class="event-images-capacity__detail">
            <%# {}を挟むとclassを読み込んでくれる %>
            <%= f.select :capacity,[["---","---"],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10]],{},{class:'select-default'} %>
          </div>
        </div>
        <div class="event-images-price">
          <%= f.label :参加価格 %>
          <span class="icon-default">必須</span><br>
          <div class="event-images-price__detail">
            <%= f.text_field :price, class: "input-default exhibit_value-box", id: "price-setting", placeholder: "例) 5000" %>
          </div>
        </div>
        <div class="event-exhibit-btn">
          <%= f.submit '出展', class: "btn-default btn-green"%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="event-container">
    <%= render partial: 'shared/main_header' %>
</div>
<section class="event-box-container">
  <%= render partial: 'shared/common_header' %>
  <div class="header-icon">
    <i class="fas fa-mitten"></i>
  </div>
  <div class="event-name"> 
    <%= @event.title %>
  </div>
    <p class="event-name__description">
      <%# 仮の説明書き（のちにサーバーサイドで編集） %>
      <%= @event.description %>
    </p>
  <div class="event-name__detail">
    <div class="event-name__detail--image">
      <div class="information-event_first-image">
        <%= image_tag @event.images.first.content.url,style: "width: 300px; height: 250px;" %>
        <%# ここに複数のイベント写真を載せる予定 %>
        <div class="event-images">
          <% @event.images.each do |image| %>
            <%= image_tag image.content.url %>
          <% end %>
        </div>
      </div>
      <div class="information-event_content-image2">
      </div>
    </div>
    <div class="event-name__detail--price clearfix">
      <span class="event_upper-row__price">参加価格 ¥ 5,000</span>
      <span class="event_upper-row__tax ">（税込）</span>
    </div>
    <table class="event-detail-table">
      <tbody>
        <tr>
          <th>出展者</th>
          <td>
            <%= link_to "#" do %>
              <span><%= @user.nickname %></span>
            <% end %>
            <%# ここにレビュー機能入れる予定 %>
            <div class="rating-star">
              <i class="fas fa-grin"></i>
               <span>2020</span>	
            </div>
          </td>
        </tr>
        <tr>
          <th>カテゴリー</th>
          <td>
            <%# ここはパンくずで実装する予定 %>
            <%= link_to "和食"  %>
            >	
            <%= link_to "和食・日本料理"  %>
            >
            <%= link_to "季節料理"  %>
          </td>
        </tr>
        <tr>
          <th>開催日程</th>
          <td>
            <div class="event-detail-date">
              2月29日（土）
            <div class="event-detail-time">
              18:30-20:30
          </td>
        </tr>
        <tr>
          <th>受付状況</th>
          <td>
            <div class="event-detail-participants">
              <div class="event-detail-state">
                受付中
              </div>
              <div class="event-detail-capacity">
                参加人数 7/8人
              </div>
          </td>
        </tr>
        <tr>
          <th>場所</th>
          <td>
            <div class="event-detail-place">
              地下鉄 明治神宮駅 徒歩3分
            </div>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="event-reservation-btn">
      <%#イベントの編集・削除機能を実装するときにunless条件分岐を使う %>
      <% if user_signed_in? %>
        <%# ログイン時 %>
        <% unless @user.id == current_user.id %>
          <%# イベントの参加人数が定員に達したときにbuyer_idに値が入り受付が終了する %>
          <% if @event.buyer_id.nil? %>
            <%= link_to confirmation_event_path(), class:"btn-default btn-green" do%>
              予約画面に進む
            <% end %>
          <% else %>
            <div class="btn-default btn-gray">
              受付終了しました
            </div>
          <% end %>
        <% else %>
          <%# 編集と削除部分は次のアプリ作成での課題とする %>
          <%= link_to "#", class:"btn-default btn-green " do%>
            編集する
          <% end %>
          <%= link_to "#", class:"btn-default btn-green" do%>
            削除する
          <% end %>
        <% end %>
      <% else %> 
        <%# 未ログイン時 %>
        <% if @event.buyer_id.nil? %>
          <%= link_to confirmation_event_path(), class:"btn-default btn-green" do%>
            予約画面に進む
          <% end %>
        <% else %>
          <div class="btn-default btn-gray">
            受付終了しました
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>
<div class="l-container clearfix"> 
  <div class="show-content">
    <div class="showroom-header">
          <div class="showroom-header__title">
            イベント参加者さんとの会話
          </div>
    </div>
    <div class="dmroom-middle clearfix">
      <%= render partial: 'messages/form' ,locals: { message: @messages } %>     
    </div>
    <div class="dmroom-form">
      <div class="new-message">

      </div>
    </div>
  </div>
</div>