config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # 仮のルーティング
  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
    collection do
      get 'events/get_category_children', defaults: { format: 'json' }
      get 'events/get_category_grandchildren', defaults: { format: 'json' }
      # get 'confirmation'
      # resources :messages
    end
    member do
      get 'confirmation'
      post 'buy'
      get 'done'
    end
    # seedで仮情報をイベントテーブルに入れたらこの位置に記述を移す
    resources :messages
    resources :entries
  end

  resources :cards, only: [:new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

     
  resources :users, only: [:show, :edit] do
    collection do
      post 'show', to: 'users#show'
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  require "payjp" 
  # before_action :set_card

  def new
    # cardがすでに登録済みの場合、showのページに戻します。
    @card = Card.new
    @card = Card.where(user_id: current_user.id).first
    redirect_to action: "show" if @card.present?    
  end

  def pay
    # payjpとCardのデータベースを作成する
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    # jsで作成したpayjpTokenがちゃんと入っているか？
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      # トークンがちゃんとあれば進めて、PAY.JPに登録されるユーザーを作成します。
      customer = Payjp::Customer.create(
      # description: '登録テスト',  # なくてもOK
      # email: current_user.email, # なくてもOK
      # metadata: {user_id: current_user.id} # なくてもOK
      # 直前のnewアクションで発行され、送られてくるトークンをここで顧客に紐付けて永久保存する
      card: params['payjp-token']
      
      )
      # PAY.JPのユーザーが作成できたので、cardモデルを登録します。
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      @card.save
      if @card.save
        redirect_to cards_path, notice: '登録が完了しました'

      else
        redirect_to action: "pay"
      end
    end
  end

  def show
    @card = Card.where(user_id: current_user.id).first
    # すでにクレジットカードが登録しているか？  
    if @card.present?
      # 登録している場合,PAY.JPからカード情報を取得する
      # PAY.JPの秘密鍵をセットする。
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      # PAY.JPから顧客情報を取得する。
      customer = Payjp::Customer.retrieve(@card.customer_id)
      # PAY.JPの顧客情報から、デフォルトで使うクレジットカードを取得する。
      @card_info = customer.cards.retrieve(@card.card_id)
      # クレジットカード情報から表示させたい情報を定義する。
      # クレジットカードの画像を表示するために、カード会社を取得
      @card_brand = @card_info.brand
      # クレジットカードの有効期限を取得
      @exp_month = @card_info.exp_month.to_s
      @exp_year = @card_info.exp_year.to_s.slice(2,3)

      # クレジットカード会社を取得したので、カード会社の画像をviewに表示させるため、ファイルを指定する。
      # カードブランドうまく分けられる様になったらコメントアウト外す
      # case @card_brand
      # when "Visa"
      #   @card_image = "visa.svg"
      # when "JCB"
      #   @card_image = "jcb.svg"
      # when "MasterCard"
      #   @card_image = "master-card.svg"
      # when "American Express"
      #   @card_image = "american_express.svg"
      # when "Diners Club"
      #   @card_image = "dinersclub.svg"
      # when "Discover"
      #   @card_image = "discover.svg"
      # end
    end
  end

  def delete
    # 今回はクレジットカードを削除するだけでなく、PAY.JPの顧客情報も削除する。これによりpayメソッドが複雑にならない。
    # PAY.JPの秘密鍵をセットして、PAY.JPから情報をする。
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    # PAY.JPの顧客情報を取得
    customer = Payjp::Customer.retrieve(@card.customer_id)
    customer.delete # PAY.JPの顧客情報を削除
    if @card.destroy # App上でもクレジットカードを削除
      redirect_to users_path, notice: "削除しました"
    else
      redirect_to users_path, alert: "削除できませんでした"
    end
  end

  private

  # def set_card
  #   @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  # end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.erb
<div class="exhibit-container">
  <%= render partial: 'shared/common_header' %>
</div>
<div class="card-container clearfix">
  <div class="card-content">
    <section class="l-chapter-container">
      <h2 class="l-chapter-head">
        支払い方法
      </h2>
      <%= form_with model:@card, url: pay_cards_path, method: :post, html: {class: "card-registration",id: 'charge-form', name: "inputForm"} do |f| %>
        <div class="event-cards__information">
          <%= f.label :カード番号 %>
          <span class="icon-default">必須</span><br>
          <%= f.text_field :card_number ,class: 'input-default', placeholder: '半角数字のみ',maxlength: "16", type: "text", id: "card_number" %>
        </div>
        <ul>
          <li>
            <img src="//assets.street-academy.com/assets/payments/supported_methods-74cee61595e49d4ad3a09c4ddc1f6f142ab0b8c865c26ef742bd856bd59c5665.png",width="480", height="30">
          </li>
        </ul>
        <div class="event-cards__expire">
          <%= f.label :有効期限 %>
          <span class="icon-default">必須</span><br>
          <%= f.select :exp_month,[["---","---"],["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{},{class:'select-default half', name: "exp_month", id:"exp_month"} %>
          <span>月</span>
          <%= f.select :exp_year,[["---","---"],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029],["30",2030]],{},{class:'select-default half', name: "exp_year", id:"exp_year"} %>
          <span>年</span><br>
        </div>
        <div class="event-cards__expire">
          <%= f.label :セキュリティーコード %>
          <span class="icon-default">必須</span><br>
          <%= f.text_field :cvc ,class: 'input-default', placeholder: 'カード背面4桁もしくは3桁の番号',maxlength: "4", id: "cvc", type: "text" %>
        </div>
        <div class="event-cards__description">
          <i class="fas fa-question-circle"></i>
          <span>
            <%= link_to "#", class:"about" do%>
              カード裏面の番号とは？
            <% end %>
          </span>
        </div>
        <div id="card_token">
          <%= f.submit '登録する', id: "token_submit", class: "btn-default btn-green "%>
        </div>
      <% end %>
    </section>
  </div>
</div>

app/views/cards/show.html.erb
<div class="exhibit-container">
  <%= render partial: 'shared/common_header' %>
</div>
<div class="card-container clearfix">
  <div class="card-content">
    <section class="l-chapter-container">
      <h2 class="l-chapter-head">
        支払い方法
      </h2>
      <%= form_with model:@card, url: delete_cards_path, method: :post, html: {class: "card-registration",id: 'charge-form', name: "inputForm"} do |f| %>
        <div class="event-cards__information">
          <%= f.label :登録クレジットカード情報 %>
        </div>
        <ul class="settings-payment-list">
          <li>
            <div class="l-step-content">
              <%# <i class="fab fa-cc-visa"></i> %>
              <img src="//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?465897195", width="49", height="20">
              <br>
              <%= "**** **** **** " + @card_info.last4 %>
              <br>
              <%= @exp_month + " / " + @exp_year %>
              <%= f.button "削除する",class: "btn-default btn-green delete-button" %>
            </div>
          </li>
        </ul>
      <% end %>
    </section>
  </div>
</div>